# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TopicDetection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 628)
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(40, 140, 72, 15))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(40, 180, 72, 15))
        self.label2.setObjectName("label2")
        self.LineEdit_para1 = QtWidgets.QLineEdit(Form)
        self.LineEdit_para1.setGeometry(QtCore.QRect(120, 130, 113, 21))
        self.LineEdit_para1.setText("")
        self.LineEdit_para1.setObjectName("LineEdit_para1")
        self.LineEdit_para2 = QtWidgets.QLineEdit(Form)
        self.LineEdit_para2.setGeometry(QtCore.QRect(120, 180, 113, 21))
        self.LineEdit_para2.setText("")
        self.LineEdit_para2.setObjectName("LineEdit_para2")
        self.Btn_SelectDoc = QtWidgets.QPushButton(Form)
        self.Btn_SelectDoc.setGeometry(QtCore.QRect(40, 50, 93, 28))
        self.Btn_SelectDoc.setObjectName("Btn_SelectDoc")
        self.Btn_Process = QtWidgets.QPushButton(Form)
        self.Btn_Process.setEnabled(True)
        self.Btn_Process.setGeometry(QtCore.QRect(50, 270, 93, 28))
        self.Btn_Process.setObjectName("Btn_Process")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(260, 60, 521, 551))
        self.textBrowser.setObjectName("textBrowser")
        self.Btn_xslx2txt = QtWidgets.QPushButton(Form)
        self.Btn_xslx2txt.setGeometry(QtCore.QRect(40, 440, 93, 28))
        self.Btn_xslx2txt.setObjectName("Btn_xslx2txt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "文本主题检测"))
        self.label1.setText(_translate("Form", "主题数"))
        self.label2.setText(_translate("Form", "参数2"))
        self.Btn_SelectDoc.setText(_translate("Form", "选择文档"))
        self.Btn_Process.setText(_translate("Form", "开始分析"))
        self.Btn_xslx2txt.setText(_translate("Form", "xslx2txt"))
