# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TopicDetection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1092, 601)
        self.label4 = QtWidgets.QLabel(Form)
        self.label4.setGeometry(QtCore.QRect(200, 20, 60, 16))
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(Form)
        self.label5.setGeometry(QtCore.QRect(630, 20, 60, 16))
        self.label5.setObjectName("label5")
        self.Btn_SelectDoc = QtWidgets.QPushButton(Form)
        self.Btn_SelectDoc.setGeometry(QtCore.QRect(9, 80, 93, 28))
        self.Btn_SelectDoc.setMinimumSize(QtCore.QSize(93, 28))
        self.Btn_SelectDoc.setMaximumSize(QtCore.QSize(93, 28))
        self.Btn_SelectDoc.setObjectName("Btn_SelectDoc")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(185, 47, 381, 531))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser2.setGeometry(QtCore.QRect(620, 50, 401, 221))
        self.textBrowser2.setObjectName("textBrowser2")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(9, 166, 51, 16))
        self.label1.setMinimumSize(QtCore.QSize(51, 16))
        self.label1.setMaximumSize(QtCore.QSize(51, 16))
        self.label1.setObjectName("label1")
        self.LineEdit_para1 = QtWidgets.QLineEdit(Form)
        self.LineEdit_para1.setGeometry(QtCore.QRect(66, 164, 113, 21))
        self.LineEdit_para1.setMinimumSize(QtCore.QSize(113, 21))
        self.LineEdit_para1.setMaximumSize(QtCore.QSize(113, 21))
        self.LineEdit_para1.setText("")
        self.LineEdit_para1.setObjectName("LineEdit_para1")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(9, 191, 21, 21))
        self.label2.setMinimumSize(QtCore.QSize(21, 21))
        self.label2.setMaximumSize(QtCore.QSize(21, 21))
        self.label2.setObjectName("label2")
        self.LineEdit_para2 = QtWidgets.QLineEdit(Form)
        self.LineEdit_para2.setGeometry(QtCore.QRect(66, 191, 113, 21))
        self.LineEdit_para2.setMinimumSize(QtCore.QSize(113, 21))
        self.LineEdit_para2.setMaximumSize(QtCore.QSize(113, 21))
        self.LineEdit_para2.setText("")
        self.LineEdit_para2.setObjectName("LineEdit_para2")
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setGeometry(QtCore.QRect(9, 218, 21, 21))
        self.label3.setMinimumSize(QtCore.QSize(21, 21))
        self.label3.setMaximumSize(QtCore.QSize(21, 21))
        self.label3.setObjectName("label3")
        self.LineEdit_para3 = QtWidgets.QLineEdit(Form)
        self.LineEdit_para3.setGeometry(QtCore.QRect(66, 218, 113, 21))
        self.LineEdit_para3.setMinimumSize(QtCore.QSize(113, 21))
        self.LineEdit_para3.setMaximumSize(QtCore.QSize(113, 21))
        self.LineEdit_para3.setObjectName("LineEdit_para3")
        self.Btn_Process = QtWidgets.QPushButton(Form)
        self.Btn_Process.setEnabled(True)
        self.Btn_Process.setGeometry(QtCore.QRect(9, 245, 93, 28))
        self.Btn_Process.setMinimumSize(QtCore.QSize(93, 28))
        self.Btn_Process.setMaximumSize(QtCore.QSize(93, 28))
        self.Btn_Process.setObjectName("Btn_Process")
        self.label6 = QtWidgets.QLabel(Form)
        self.label6.setGeometry(QtCore.QRect(630, 310, 60, 16))
        self.label6.setObjectName("label6")
        self.Btn_Result = QtWidgets.QPushButton(Form)
        self.Btn_Result.setGeometry(QtCore.QRect(9, 421, 93, 28))
        self.Btn_Result.setMinimumSize(QtCore.QSize(93, 28))
        self.Btn_Result.setMaximumSize(QtCore.QSize(93, 28))
        self.Btn_Result.setObjectName("Btn_Result")
        self.textBrowser3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser3.setGeometry(QtCore.QRect(620, 340, 411, 231))
        self.textBrowser3.setObjectName("textBrowser3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "文本主题检测"))
        self.label4.setText(_translate("Form", "终端输出"))
        self.label5.setText(_translate("Form", "文本聚类"))
        self.Btn_SelectDoc.setText(_translate("Form", "选择文档"))
        self.label1.setText(_translate("Form", "主题数"))
        self.label2.setText(_translate("Form", "α"))
        self.label3.setText(_translate("Form", "β"))
        self.Btn_Process.setText(_translate("Form", "开始分析"))
        self.label6.setText(_translate("Form", "文档查看"))
        self.Btn_Result.setText(_translate("Form", "浏览文档"))
